<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial migration: creates health_log table.
 *
 * If you have an existing database created via doctrine:schema:create,
 * mark this migration as already executed:
 *
 *   php bin/console doctrine:migrations:version --add --all
 */
final class Version20260811130655 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial database schema (health_log).';
    }

    public function up(Schema $schema): void
    {
        // Schema generated by doctrine:migrations:diff from entity metadata
        $this->addSql('CREATE TABLE health_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, systolic INTEGER DEFAULT NULL, diastolic INTEGER DEFAULT NULL, heart_rate INTEGER DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, emoji VARCHAR(10) NOT NULL)');
    }

    public function down(Schema $schema): void
    {
        // Revert schema to empty state
        $this->addSql('DROP TABLE health_log');
    }
}
